function Arrow(){
	this.x=50;
	this.y=50;
	this.color="#ffff00";
	this.rotation=0;
}
Arrow.prototype.draw=function(context){
	context.save();
	context.translate(this.x,this.y);
	context.rotate(this.rotation);
	context.fillStyle=this.color;
	context.lineWidth=2;
	context.beginPath();
	context.moveTo(-50,-25);
	context.lineTo(0,-25);
	context.lineTo(0,-50);
	context.lineTo(50,0);
	context.lineTo(0,50);
	context.lineTo(0,25);
	context.lineTo(-50,25);
	context.lineTo(-50,-25);
	context.closePath();
	context.fill();
	context.stroke();
	context.restore();
}